name: "springboot-app-plugin"
description: Plugin to Spring
type: plugin
languages:
  - "kotlin"
tags:
  - "default_stack"  
inputs:
  - label: "Do you want to expose rest api: "
    type: bool
    name: "starter-web"
    default: true