name: "springboot-app-plugin"
description: Plugin to configure Spring Boot
types:
  - app
languages:
  - kotlin
tags:
  - spring
inputs:
  - label: "Do you want to expose rest api: "
    type: bool
    name: "starter_web"
    default: true